name: Build and Push to Multiple Registries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DO_REGISTRY: registry.digitalocean.com
  DO_REGISTRY_NAME: deusnextjs
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: next16
  DOCKERFILE_PATH: prod.dockerfile

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Para GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login a DigitalOcean Registry
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      # Login a GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo
        run: echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Build una sola vez con múltiples tags
      - name: Build Docker image
        run: |
          docker build \
            --file ${{ env.DOCKERFILE_PATH }} \
            --tag ${{ env.DO_REGISTRY }}/${{ env.DO_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.GHCR_REGISTRY }}/${{ steps.repo.outputs.name }}:latest \
            .

      - name: Check image size
        run: |
          echo "📊 Image size information:"
          docker images ${{ env.DO_REGISTRY }}/${{ env.DO_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest \
            --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"

      # Push a DigitalOcean Registry
      - name: Push to DigitalOcean Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.DO_REGISTRY }}/${{ env.DO_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest

      # Push a GitHub Container Registry
      - name: Push to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.GHCR_REGISTRY }}/${{ steps.repo.outputs.name }}:latest

      - name: Cleanup old untagged images from DigitalOcean
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "🧹 Cleaning up untagged images from DigitalOcean..."
          doctl registry garbage-collection start --include-untagged-manifests --force ${{ env.DO_REGISTRY_NAME }} || echo "⚠️  Garbage collection already running or not available"

      - name: Output image info
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "🚀 Images pushed successfully!"
          echo ""
          echo "📦 DigitalOcean Registry:"
          echo "   ${{ env.DO_REGISTRY }}/${{ env.DO_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest"
          echo ""
          echo "📦 GitHub Container Registry (for Railway):"
          echo "   ${{ env.GHCR_REGISTRY }}/${{ steps.repo.outputs.name }}:latest"
          echo ""
          echo "💡 Use the GHCR image in Railway!"
